name    'alkivi-backuppc'
version '0.1.4'
source 'https://github.com/alkivi-sas/puppet-backuppc'
author 'alkivi'
license 'LGPLv3'
summary 'Controls backupPC and clients'
description 'Setup backupPC and handle client configuration in puppet'
project_page 'https://github.com/alkivi-sas/puppet-backuppc'
dependency 'puppetlabs/stdlib', '>=3.0.0'
dependency 'puppetlabs/concat', '1.0.0'
dependency 'alkivi/alkivi_base', '>=0.0.1'
